// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfileFromLink(arg1) {
  return window['go']['main']['App']['AddProfileFromLink'](arg1);
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveGeneralSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveGeneralSettings'](arg1, arg2, arg3, arg4);
}

export function SetActiveProfile(arg1) {
  return window['go']['main']['App']['SetActiveProfile'](arg1);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}
