// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {engine} from '../models';

export function Connect():Promise<void>;

export function Disconnect():Promise<void>;

export function GetSettings():Promise<main.Settings>;

export function GetStatus():Promise<engine.StatusSnapshot>;

export function ParseLink(arg1:string):Promise<main.Settings>;

export function Quit():Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function Show():Promise<void>;
