// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSubscriptionFromLink(arg1) {
  return window['go']['main']['App']['AddSubscriptionFromLink'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function CreateLocalRoutingRuleSet(arg1) {
  return window['go']['main']['App']['CreateLocalRoutingRuleSet'](arg1);
}

export function DeleteLocalRoutingRuleSet(arg1) {
  return window['go']['main']['App']['DeleteLocalRoutingRuleSet'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function ExportRoutingRuleSet(arg1, arg2) {
  return window['go']['main']['App']['ExportRoutingRuleSet'](arg1, arg2);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HandleExternalLink(arg1) {
  return window['go']['main']['App']['HandleExternalLink'](arg1);
}

export function ImportLocalRoutingRuleSet(arg1) {
  return window['go']['main']['App']['ImportLocalRoutingRuleSet'](arg1);
}

export function MeasureNodeLatencies(arg1) {
  return window['go']['main']['App']['MeasureNodeLatencies'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RefreshSubscription(arg1) {
  return window['go']['main']['App']['RefreshSubscription'](arg1);
}

export function SaveGeneralSettings(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveGeneralSettings'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SetActiveNode(arg1, arg2) {
  return window['go']['main']['App']['SetActiveNode'](arg1, arg2);
}

export function SetActiveSubscription(arg1) {
  return window['go']['main']['App']['SetActiveSubscription'](arg1);
}

export function SetPanelRoutingEnabled(arg1) {
  return window['go']['main']['App']['SetPanelRoutingEnabled'](arg1);
}

export function SetSystemWideMode(arg1) {
  return window['go']['main']['App']['SetSystemWideMode'](arg1);
}

export function Show() {
  return window['go']['main']['App']['Show']();
}

export function UpdateLocalRoutingRuleSet(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateLocalRoutingRuleSet'](arg1, arg2, arg3);
}
