// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {routing} from '../models';
import {engine} from '../models';

export function AddSubscriptionFromLink(arg1:string):Promise<main.Subscription>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function Connect():Promise<void>;

export function CreateLocalRoutingRuleSet(arg1:string):Promise<routing.RuleSet>;

export function DeleteLocalRoutingRuleSet(arg1:string):Promise<void>;

export function DeleteSubscription(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function DownloadAndInstallUpdate(arg1:string):Promise<void>;

export function ExportRoutingRuleSet(arg1:routing.RuleSet,arg2:string):Promise<main.RoutingExportResult>;

export function GetAppSettings():Promise<main.AppSettings>;

export function GetAppVersion():Promise<string>;

export function GetLogs():Promise<Array<string>>;

export function GetStatus():Promise<engine.StatusSnapshot>;

export function HandleExternalLink(arg1:string):Promise<void>;

export function ImportLocalRoutingRuleSet(arg1:string):Promise<main.RoutingImportResult>;

export function MeasureNodeLatencies(arg1:string):Promise<Record<string, number>>;

export function OpenURL(arg1:string):Promise<void>;

export function Quit():Promise<void>;

export function RefreshSubscription(arg1:string):Promise<main.Subscription>;

export function SaveGeneralSettings(arg1:number,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean,arg6:number,arg7:boolean):Promise<void>;

export function SetActiveNode(arg1:string,arg2:string):Promise<void>;

export function SetActiveSubscription(arg1:string):Promise<void>;

export function SetPanelRoutingEnabled(arg1:boolean):Promise<void>;

export function SetSystemWideMode(arg1:boolean):Promise<void>;

export function Show():Promise<void>;

export function UpdateLocalRoutingRuleSet(arg1:string,arg2:string,arg3:Array<routing.Rule>):Promise<routing.RuleSet>;
